name: Android CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Download PDF.js assets
      run: |
        wget -O pdfjs.zip https://github.com/mozilla/pdf.js/releases/download/v3.11.174/pdfjs-3.11.174-legacy-dist.zip
        mkdir -p app/src/main/assets/pdfjs
        unzip -o pdfjs.zip -d app/src/main/assets/pdfjs
        rm pdfjs.zip

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew || true

    - name: Build with Gradle
      run: ./gradlew assembleDebug
